### ISSUE TITLE
why does the docs folder contains a .pages file?

### ISSUE THREAD

**Issue by 2bndy5** [Mmessiter/LockDownRadioControl#1]
I can't view the doc named LDRC1.pages. VSCode tells me
![image](https://user-images.githubusercontent.com/14963867/133943904-972a10e0-fe10-4dd7-8c69-b0e84a620b80.png)

Usually this means it is a binary file. But, if this means it uses a unusually text encoding, it should be amended to use UTF-8 encoding.

Typically (for security reasons), we devs try to avoid uploading any binary files to repositories ("repos" for short) including .hex, .elf, and .bin files - picture files (png, jpg, bmp) are an exception.

**Comment by Mmessiter** [comment]
Sorry! It's only a brief doc file. I'll fix it!

**Comment by 2bndy5** [comment]
you can close this issue when it is fixed.

**Comment by Mmessiter** [comment]
Ok - I'll try to fix that in the morning. Bedtime now! Thank you.

**Comment by Mmessiter** [comment]
I'd started writing the documentation using "Pages". It seems this wasn't a good choice. Which text editor is best for GitHub use?

**Comment by 2bndy5** [comment]
github prefers you use .md files which uses MarkDown syntax. There are different "flavors" of markdown ("MD" for short), namely [the github flavored md](https://guides.github.com/features/mastering-markdown/).

Notice the README.md is a markdown file. MD is also widely used to genereate static documentation in mkdocs, but that is another topic for a later time...

**Comment by Mmessiter** [comment]
Thanks- I'll look into .md files tomorrow and fix that issue! 

As you see - there's a lot I just didn't know.

**Comment by Mmessiter** [comment]
... it's 12.40 AM here!  zzzzz

**Comment by timspray** [comment]
Have converted LDRC1.pages file to LDRC User Manual ver 0.1.pdf

**Comment by 2bndy5** [comment]
Good to hear! I just want to mention that we could use [mkdocs](https://www.mkdocs.org/) to take .md files and generate html or pdf files. I'm more experienced in using [Sphinx](https://www.sphinx-doc.org/en/master/) software to do the same tasks. We can discuss this more when everything is matured (documenting the API can be done straight from the source code with Sphinx but not with mkdocs).

**Comment by Mmessiter** [comment]
Oh thank you that's good. If PDFs are ok then maybe I should leave the documentation in "pages" while working on it more.

**Comment by Mmessiter** [comment]
Perhaps the most urgent requirement right now is for me to add in to the docs how to build this thing! I'll work today on that, and make it a .pdf before pushing it.

**Comment by 2bndy5** [comment]
I would urge different files for different aspects of the project; ie 1 doc for building hardware, 1 doc for preparing firmware, 1 doc for application usage like the user manual...

**Comment by Mmessiter** [comment]
Ok I had thought one file but I'm happy to make several, as MD files and pdfs - 

1. User manual (as for a commercial radio)
2. Build your own (assembly instructions)
3. Analysis and discussion of software inner functionality (for those working on the code). 

How about that for a plan?

**Comment by 2bndy5** [comment]
That sounds great. My scrolling finger is already thanking you!

**Comment by Mmessiter** [comment]
Excellent. 😊
It's my project today. First construction/building  - without which I'm the only person with working hardware!

**Comment by Mmessiter** [comment]
I just ran a little test:
Having got the latest reformatted versions onto my local disc, I compiled the transmitter code and put it into a transmitter. It worked fine. 

Then I did the same for the receiver code.
It behaved as if the new RF24 library was in it. That is, it lost many many packets. So something else must have changed at least in the receiver code. I don't know what. Maybe it's including that new library?

The transmitter might too be using new library- as that was always ok.

I then put Sunday's receiver version back into that receiver. It worked perfectly. Error fixed.

Perhaps I should now revert GitHub to the working version ?!

**Comment by Mmessiter** [comment]
Ok I did another test:

I took the newly nicely formatted receiver code and put it where Sunday's version was. So ONLY the main.cpp was different. That worked fine. Hence the problem is in library use - most likely it's including wrong RF24 library I guess. I await your wisdom! 😄

**Comment by 2bndy5** [comment]
its now 5:39 AM here, I'm going to bed... I know my sleeping habits are terrible 😆, but it has proven helpful when collaborating with people on the other side of the world.

**Comment by Mmessiter** [comment]
Thank you for this! 

I agree absolutely. I already knew a pointer would be a better plan - but sadly I only knew how to do that with confidence in 8086 assembler! (Somehow the syntax of C++ pointers still sometimes confuses me.) 

I will implement the change you propose and test results. 

And I'll try to continue to learn. I feel I'm in the right place! 

Is it not rather late at night in California?!

**Comment by 2bndy5** [comment]
> Somehow the syntax of C++ pointers still sometimes confuses me

You and all other C++ programmers (me included ... sometimes). Some pros never fully get this down, but practice is the best way to learn.

**Comment by Mmessiter** [comment]
I'll practice! 😄

**Comment by Mmessiter** [comment]
Incidentally I'm using the older library for the moment also for the transmitter. 
Reason is: "model memory exchange" (file copying) between transmitters involves receive on one of them of course. This became unreliable with most recent library but never fails with older one.
