### ISSUE TITLE
using SBUS.write() properly?

### ISSUE THREAD

**Issue by 2bndy5** [Mmessiter/LockDownRadioControl#12]
Given the last status email involving an undefined behavior with the `SBUS`, I looked into the SBUS lib usage a little closer...

https://github.com/Mmessiter/LockDownRadioControl/blob/2328949612c8063c7c7729bbaf842cb490f4606c/ReceiverCode/src/main.cpp#L123-L126

shown above is the snippet that erroneously passes an array to `SBUS.write()`

`SbusChannels` is declared as a uint16_t array of  elements using https://github.com/Mmessiter/LockDownRadioControl/blob/2328949612c8063c7c7729bbaf842cb490f4606c/ReceiverCode/src/main.cpp#L52 which amounts to a buffer of 48 bytes. This seems intentional given the code comments, but no rationality was given.

`SBUS.write(uin16_t*)` expects the buffer to only have 32 bytes (that's 16 elements in a uint16_t array). Furthermore, I'm not sure that you're passing the pointer of the buffer properly. I'd recommend:
```cpp
     MySbus.write(SbusChannels);                     // Send SBUS data 
```
Notice there is no need to specify the first element in the array (`[0]`) or use the de-reference operator (`&`) because the array's name can act like a pointer by itself.

<details><summary>source code for <code>SBUS.write()</code></summary>

```cpp
/* write SBUS packets */
void SBUS::write(uint16_t* channels)
{
    static uint8_t packet[25];
    /* assemble the SBUS packet */
    // SBUS header
    packet[0] = _sbusHeader;
    // 16 channels of 11 bit data
    if (channels) {
        packet[1] = (uint8_t) ((channels[0] & 0x07FF));
        packet[2] = (uint8_t) ((channels[0] & 0x07FF)>>8 | (channels[1] & 0x07FF)<<3);
        packet[3] = (uint8_t) ((channels[1] & 0x07FF)>>5 | (channels[2] & 0x07FF)<<6);
        packet[4] = (uint8_t) ((channels[2] & 0x07FF)>>2);
        packet[5] = (uint8_t) ((channels[2] & 0x07FF)>>10 | (channels[3] & 0x07FF)<<1);
        packet[6] = (uint8_t) ((channels[3] & 0x07FF)>>7 | (channels[4] & 0x07FF)<<4);
        packet[7] = (uint8_t) ((channels[4] & 0x07FF)>>4 | (channels[5] & 0x07FF)<<7);
        packet[8] = (uint8_t) ((channels[5] & 0x07FF)>>1);
        packet[9] = (uint8_t) ((channels[5] & 0x07FF)>>9 | (channels[6] & 0x07FF)<<2);
        packet[10] = (uint8_t) ((channels[6] & 0x07FF)>>6 | (channels[7] & 0x07FF)<<5);
        packet[11] = (uint8_t) ((channels[7] & 0x07FF)>>3);
        packet[12] = (uint8_t) ((channels[8] & 0x07FF));
        packet[13] = (uint8_t) ((channels[8] & 0x07FF)>>8 | (channels[9] & 0x07FF)<<3);
        packet[14] = (uint8_t) ((channels[9] & 0x07FF)>>5 | (channels[10] & 0x07FF)<<6);
        packet[15] = (uint8_t) ((channels[10] & 0x07FF)>>2);
        packet[16] = (uint8_t) ((channels[10] & 0x07FF)>>10 | (channels[11] & 0x07FF)<<1);
        packet[17] = (uint8_t) ((channels[11] & 0x07FF)>>7 | (channels[12] & 0x07FF)<<4);
        packet[18] = (uint8_t) ((channels[12] & 0x07FF)>>4 | (channels[13] & 0x07FF)<<7);
        packet[19] = (uint8_t) ((channels[13] & 0x07FF)>>1);
        packet[20] = (uint8_t) ((channels[13] & 0x07FF)>>9 | (channels[14] & 0x07FF)<<2);
        packet[21] = (uint8_t) ((channels[14] & 0x07FF)>>6 | (channels[15] & 0x07FF)<<5);
        packet[22] = (uint8_t) ((channels[15] & 0x07FF)>>3);
    }
    // flags
    packet[23] = 0x00;
    // footer
    packet[24] = _sbusFooter;
    #if defined(__MK20DX128__) || defined(__MK20DX256__) // Teensy 3.0 || Teensy 3.1/3.2
        // use ISR to send byte at a time,
        // 130 us between bytes to emulate 2 stop bits
        noInterrupts();
        memcpy(&PACKET,&packet,sizeof(packet));
        interrupts();
        serialTimer.priority(255);
        serialTimer.begin(sendByte,130);
    #else
        // write packet
        _bus->write(packet,25);
    #endif
}
```
</details>

**Comment by 2bndy5** [comment]
I would also suggest explicitly casting the result from `map()` as a uint16_t value.
https://github.com/Mmessiter/LockDownRadioControl/blob/2328949612c8063c7c7729bbaf842cb490f4606c/ReceiverCode/src/main.cpp#L111-L119

```cpp
             SbusChannels[j] = static_cast<uint16_t>(map(ReceivedData[j], MINMICROS, MAXMICROS, RANGEMIN, RANGEMAX));
```

**Comment by Mmessiter** [comment]
Thank you Brendan!

I will make the change that you suggest.

I’m learning… I apologise it seems slow!

I just made the low battery warning user-definable

…

**Comment by Mmessiter** [comment]
Ah - ok!! Thank you ….

**Comment by Mmessiter** [comment]
I have done the updates you suggested!

Thank you!

I reduce that array to one element greater than needed instead of eight. … Sometimes I worry that the array contents might exceed dimensioning!

It still works fine.  I don’t yet understand why I needed to change this line:

SbusChannels[j] = static_cast<uint16_t>(map(ReceivedData[j], MINMICROS, MAXMICROS, RANGEMIN, RANGEMAX));

I wonder if you can tell me?

With all best wishes,

Malcolm

**Comment by 2bndy5** [comment]
I'm not sure how the source code for `map()` was written. It could strictly return `long` data type. Type casting it makes it clear to both the compiler and other devs that a `uint16_t` data type is assigned to each element.

BTW this is a C++ type cast:
```cpp
const_cast<data_type>(object); // toggles const-ness
static_cast<data_type>(object);
reinterpret_cast<data_type>(object); // this can be destructive
```
The above casting is attempted (in the shown order/priority) when doing a C type cast
```c
(data_type)object;
```
Although the C type casting seems easier to read/write it can be more destructive than intended because it causes some guessing on the compilers' behalf.

- I hardly ever use `const_cast`.
- I commonly use `static_cast`.
- I only use `reinterpret_cast` when I absolutely need to (typically when the data types from/to aren't similar enough).

**Comment by 2bndy5** [comment]
closing this as it seems to be satisfied by https://github.com/Mmessiter/LockDownRadioControl/commit/fdf05ff96df80e3746d7ae304b4f394b0241fdcc

Please re-open if the suggested changes caused any unexpected behavior in hardware tests.

**Comment by Mmessiter** [comment]
Thank you very much! Sorry I’ve such a lot still to learn! 
… the radio is becoming rather good now!
